version: '3'

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskr3
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      FLASK_APP: /app/app.py
#      FLASK_ENV: development
